version: '3.8'

services:
  oracle-database:
    image: gvenzl/oracle-xe:21
    container_name: oracle-database
    ports:
      - "1521:1521"
    restart: on-failure
    environment:
      ORACLE_PASSWORD: tricao123
      APP_USER: tricao
      APP_USER_PASSWORD: oracledb
    volumes:
      - oracle_db:/opt/oracle/oradata
    networks:
      - debezium_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    restart: on-failure
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - debezium_network

  broker:
    image: confluentinc/cp-server:7.9.1
    container_name: broker
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    restart: on-failure
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - debezium_network

  debezium-connect:
    image: debezium/connect:2.4
    container_name: debezium-connect
    ports:
      - "8083:8083"
    depends_on:
      - broker
    restart: on-failure
    environment:
      BOOTSTRAP_SERVERS: broker:29092
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
    volumes:
      - debezium_connectors:/kafka/connect
    networks:
      - debezium_network

  debezium-ui:
    image: debezium/debezium-ui:2.4
    container_name: debezium-ui
    ports:
      - "8080:8080"
    depends_on:
      - debezium-connect
    restart: on-failure
    environment:
      KAFKA_CONNECT_URIS: http://debezium-connect:8083
    networks:
      - debezium_network

volumes:
  oracle_db:
  kafka_data:
  debezium_connectors:

networks:
  debezium_network: