version: '3.8'

services:
  oracle-database:
    image: gvenzl/oracle-xe:21
    container_name: oracle-database
    ports:
      - "1521:1521"
    restart: on-failure
    environment:
      ORACLE_PASSWORD: admin123
      APP_USER: userdb
      APP_USER_PASSWORD: oracledb
    volumes:
      - oracle_db:/opt/oracle/oradata
    networks:
      - debezium_network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: on-failure
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    command: >
      postgres -c wal_level=logical
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - debezium_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    container_name: zookeeper
    restart: on-failure
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - debezium_network

  broker:
    image: confluentinc/cp-server:7.9.0
    container_name: broker
    restart: on-failure
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - debezium_network

  debezium-connect:
    image: debezium/connect:2.4
    container_name: debezium-connect
    restart: on-failure
    depends_on:
      - broker
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: broker:29092
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
    volumes:
      - debezium_connectors:/kafka/connect
      - ./jars:/kafka/connect/jars
    networks:
      - debezium_network

  debezium-ui:
    image: debezium/debezium-ui:2.4
    container_name: debezium-ui
    restart: on-failure
    depends_on:
      - debezium-connect
    ports:
      - "8080:8080"
    environment:
      KAFKA_CONNECT_URIS: http://debezium-connect:8083
    networks:
      - debezium_network

volumes:
  oracle_db:
  kafka_data:
  debezium_connectors:
  postgres_data:

networks:
  debezium_network: